title: Manimala's site
author: orsmanimala
email: manimala@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog.

# social links
github_username:  orsmanimala

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
